fixtures:
  repositories:
    apt:
      repo: 'git://github.com/puppetlabs/puppetlabs-apt'
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib'
    concat:
      repo: 'git://github.com/puppetlabs/puppetlabs-concat'
    epel:
      repo: 'https://github.com/stahnma/puppet-module-epel'
  symlinks:
    'collectd': "#{source_dir}"
